version: '3'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./dist:/usr/share/nginx/html/docs
    environment:
      API_URL: docs/documents.yaml

  swagger-api:
    image: danielgtaylor/apisprout:latest
    container_name: "swagger-api"
    ports:
      - "8083:8000"
    volumes:
      - ./dist/documents.yaml:/documents.yaml
    entrypoint: /usr/local/bin/apisprout /documents.yaml --watch

  swagger-watch:
    image: node:latest
    container_name: "swagger-watch"
    command: bash -c "yarn install && yarn watch"
    volumes:
      - .:/work
    working_dir: /work
